version: '3.8'

services:
  ai-compoiso-frontend:
    image: ghcr.io/funy-z/ai-compoiso-frontend:latest
    volumes:
      - frontend-share:/app/frontend-share

  ai-compoiso-backend:
    image: funy-z/ai-compoiso-backend:latest
    environment:
      - ENVIRONMENT=production
    volumes:
      - /data/environ:/app/environ:ro
      - /var/log/ai_compoiso_backend:/app/logs
      - /data/sqlite3_db:/app/sqlite3_db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - frontend-share:/usr/share/nginx/html:ro
      - /app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /app/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - ai-compoiso-frontend
      - ai-compoiso-backend

volumes:
  frontend-share:
    driver: local
    driver_opts:
      type: none
      device: /app/frontend-share
      o: bind
