version: '3.8'

services:
  ai-composiso-frontend:
    image: ghcr.io/funy-z/ai-composiso-frontend:e96efb6d36f2d5d197c05aaf5e1e1b7abf635654
    volumes:
      - frontend-share:/app/frontend-share

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - frontend-share:/usr/share/nginx/html:ro
      - /app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /app/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - ai-composiso-frontend

volumes:
  frontend-share:
    driver: local
    driver_opts:
      type: none
      device: /app/frontend-share
      o: bind
